dist: trusty
sudo: required
language: node_js
node_js:
- '8'
- '10'

deploy:
  provider: heroku
  api_key:
    secure: kv4RwF5ZGYUbgmaX9jESGAasxKPMSkAD8NUShwIE+H//Z/xPtnyJ4zbIYb+NTPljS2lZGXGxxhtxVzC7bX+q/Y+k7aKjY1gcZHEXWKHF2RIIB/KTESonuootvvetbKQVYx5bqAakCXkXmbq+/3yRD89q6PJMGsw5rCx7fEpOil3yITfneRGul/8ZDhtgGLSQtsa0iqVHVYnYFnEI1B2EsYHrCmyGWFen0wKKZkqE2ryxw2KevsOEm7dlz4xtjIQP/zTdFDwCL1IqkXYpvGMMBnnntGkPQBjGoRiJfYRQVQi+XC3qhPg+XG/SdoExiHoEc+uOlf8VqwTn3Z1uPEvMzZP+02r5EhupeOZ9rMXTgb6EYXN6q8i5agkXF8QujUYFz5NZs451YF3PFxyq7KKTrtuKd0KujGOkVzA0KpIjl2tRztxvej3Q2IPblAMXH+Rq9pem/HAH2Oxr+stT7dIOawHh5bk3yTMuLDvsEFbneELEHStzWzWFIhyBIXtTEEdSJY9moh76lkZY83ireE6U3zmLftJ7+TWBdFTiUe0mJxPoI8MWAr1rjcXNVjE7iUXx8q4rNPhVlJ3uzKk+qZ+P5VjNQLUAT1QE/IdF6h7V7nVcn5XeVPvIIcIa5b1tBTqmYBO42S4CkQ+plXsfVbiKACgPEmkeGU9bIqomQaFlcbQ=
  app: pigallery2
  on:
    repo: bpatrik/pigallery2
    node: '8'
cache:
  directories:
  - node_modules

addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
